"""
Prometheus Metrics Exporter for Eleanor Platform

Exposes trading metrics for Prometheus scraping and Grafana visualization.
"""

from prometheus_client import Counter, Gauge, Histogram, Summary, start_http_server
import logging
from threading import Thread
from typing import Optional


class ArbitrageMetrics:
    """
    Prometheus metrics for arbitrage trading

    Exposes metrics on :8000/metrics by default
    """

    def __init__(self, port: int = 8000):
        """
        Initialize Prometheus metrics

        Args:
            port: HTTP port for metrics endpoint (default 8000)
        """
        self.port = port

        # Trading metrics
        self.trades_total = Counter(
            'arbitrage_trades_total',
            'Total number of arbitrage trades executed',
            ['status', 'priority']  # labels: success/failed, high/medium/low
        )

        self.trades_profit_usd = Counter(
            'arbitrage_profit_usd_total',
            'Total profit in USD from all trades'
        )

        self.current_capital = Gauge(
            'arbitrage_capital_usd',
            'Current trading capital in USD'
        )

        self.trade_size_usd = Histogram(
            'arbitrage_trade_size_usd',
            'Trade size distribution in USD',
            buckets=[100, 500, 1000, 2500, 5000, 10000, 25000]
        )

        self.trade_profit_pct = Histogram(
            'arbitrage_profit_pct',
            'Trade profit percentage distribution',
            buckets=[0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0]
        )

        # Scraping metrics
        self.scrape_duration_seconds = Histogram(
            'arbitrage_scrape_duration_seconds',
            'Time taken to scrape all DEXs',
            buckets=[10, 30, 60, 120, 180, 300]
        )

        self.pairs_scraped = Gauge(
            'arbitrage_pairs_scraped',
            'Number of trading pairs successfully scraped'
        )

        self.dex_prices_collected = Counter(
            'arbitrage_dex_prices_total',
            'Total DEX price points collected',
            ['dex']  # label: uniswap_v3, pancakeswap_v3, etc.
        )

        # AI metrics
        self.signals_generated = Counter(
            'arbitrage_signals_generated_total',
            'Total arbitrage signals generated by AI',
            ['priority']  # label: high, medium, low
        )

        self.ai_confidence = Histogram(
            'arbitrage_ai_confidence',
            'AI confidence score distribution',
            buckets=[0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]
        )

        self.ai_risk_score = Histogram(
            'arbitrage_ai_risk_score',
            'AI risk score distribution',
            buckets=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
        )

        # Cycle metrics
        self.cycles_total = Counter(
            'arbitrage_cycles_total',
            'Total number of trading cycles completed'
        )

        self.cycle_duration_seconds = Histogram(
            'arbitrage_cycle_duration_seconds',
            'Total cycle duration (scrape + analyze + execute)',
            buckets=[60, 120, 180, 300, 600, 900]
        )

        # Error metrics
        self.errors_total = Counter(
            'arbitrage_errors_total',
            'Total number of errors encountered',
            ['type']  # label: scrape_error, trade_error, ai_error
        )

        # Performance metrics
        self.win_rate = Gauge(
            'arbitrage_win_rate',
            'Current win rate (successful trades / total trades)'
        )

        self.total_return_pct = Gauge(
            'arbitrage_total_return_pct',
            'Total return percentage since start'
        )

        self.sharpe_ratio = Gauge(
            'arbitrage_sharpe_ratio',
            'Current Sharpe ratio'
        )

        # DEX-specific metrics
        self.dex_opportunities = Counter(
            'arbitrage_dex_opportunities_total',
            'Opportunities found per DEX pair',
            ['buy_dex', 'sell_dex']
        )

        # System metrics
        self.uptime_seconds = Gauge(
            'arbitrage_uptime_seconds',
            'Total uptime in seconds'
        )

        self.last_scrape_timestamp = Gauge(
            'arbitrage_last_scrape_timestamp',
            'Unix timestamp of last successful scrape'
        )

        logging.info(f"Prometheus metrics initialized on port {port}")

    def start_server(self):
        """Start the Prometheus metrics HTTP server in background thread"""
        def _start():
            try:
                start_http_server(self.port)
                logging.info(f"✓ Prometheus metrics server started on http://localhost:{self.port}/metrics")
            except Exception as e:
                logging.error(f"Failed to start metrics server: {e}")

        thread = Thread(target=_start, daemon=True)
        thread.start()

    # Helper methods for recording metrics

    def record_trade(self, success: bool, priority: str, profit_usd: float,
                     size_usd: float, profit_pct: float):
        """Record a trade execution"""
        status = 'success' if success else 'failed'
        self.trades_total.labels(status=status, priority=priority).inc()

        if success:
            self.trades_profit_usd.inc(profit_usd)
            self.trade_size_usd.observe(size_usd)
            self.trade_profit_pct.observe(profit_pct)

    def record_scrape(self, duration_seconds: float, pairs_count: int):
        """Record a scraping cycle"""
        self.scrape_duration_seconds.observe(duration_seconds)
        self.pairs_scraped.set(pairs_count)

    def record_dex_price(self, dex_name: str):
        """Record a DEX price point collected"""
        self.dex_prices_collected.labels(dex=dex_name).inc()

    def record_signal(self, priority: str, confidence: float, risk: float,
                     buy_dex: str, sell_dex: str):
        """Record an AI-generated arbitrage signal"""
        self.signals_generated.labels(priority=priority).inc()
        self.ai_confidence.observe(confidence)
        self.ai_risk_score.observe(risk)
        self.dex_opportunities.labels(buy_dex=buy_dex, sell_dex=sell_dex).inc()

    def record_cycle(self, duration_seconds: float):
        """Record a complete trading cycle"""
        self.cycles_total.inc()
        self.cycle_duration_seconds.observe(duration_seconds)

    def record_error(self, error_type: str):
        """Record an error"""
        self.errors_total.labels(type=error_type).inc()

    def update_capital(self, capital_usd: float):
        """Update current capital"""
        self.current_capital.set(capital_usd)

    def update_performance(self, win_rate: float, total_return_pct: float,
                          sharpe_ratio: Optional[float] = None):
        """Update performance metrics"""
        self.win_rate.set(win_rate)
        self.total_return_pct.set(total_return_pct)
        if sharpe_ratio is not None:
            self.sharpe_ratio.set(sharpe_ratio)

    def update_uptime(self, uptime_seconds: float):
        """Update uptime metric"""
        self.uptime_seconds.set(uptime_seconds)

    def update_last_scrape_time(self, timestamp: float):
        """Update last scrape timestamp"""
        self.last_scrape_timestamp.set(timestamp)


# Global metrics instance
_metrics: Optional[ArbitrageMetrics] = None


def get_metrics(port: int = 8000) -> ArbitrageMetrics:
    """
    Get or create the global metrics instance

    Args:
        port: HTTP port for metrics endpoint

    Returns:
        ArbitrageMetrics instance
    """
    global _metrics
    if _metrics is None:
        _metrics = ArbitrageMetrics(port=port)
    return _metrics


def start_metrics_server(port: int = 8000):
    """
    Start the Prometheus metrics server

    Args:
        port: HTTP port for metrics endpoint
    """
    metrics = get_metrics(port=port)
    metrics.start_server()
